"""create initial workforceiq schema

Revision ID: ae7dc1607d02
Revises:
Create Date: 2026-08-09 16:34:49.153540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7dc1607d02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=False),
    sa.Column('availability_status', sa.String(length=50), nullable=False),
    sa.Column('utilization_percentage', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('experience_years >= 0', name='ck_employee_experience_nonnegative'),
    sa.CheckConstraint('utilization_percentage >= 0 AND utilization_percentage <= 100', name='ck_employee_utilization_range'),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_table('permissions',
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_name')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=150), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_project_date_range'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=True)
    op.create_table('certifications',
    sa.Column('certification_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('certification_name', sa.String(length=150), nullable=False),
    sa.Column('issuing_authority', sa.String(length=150), nullable=True),
    sa.Column('certification_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expiry_date IS NULL OR issue_date IS NULL OR expiry_date >= issue_date', name='ck_certification_date_range'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('certification_id')
    )
    op.create_index(op.f('ix_certifications_employee_id'), 'certifications', ['employee_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('employee_skill_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=False),
    sa.Column('years_experience', sa.Float(), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('years_experience >= 0', name='ck_employee_skill_experience_nonnegative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.PrimaryKeyConstraint('employee_skill_id'),
    sa.UniqueConstraint('employee_id', 'skill_id', name='uq_employee_skill')
    )
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_skill_id'), 'employee_skills', ['skill_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_permission_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('staffing_requirements',
    sa.Column('staffing_requirement_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.Column('required_experience', sa.Float(), nullable=False),
    sa.Column('required_proficiency', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_staffing_date_range'),
    sa.CheckConstraint('required_experience >= 0', name='ck_staffing_experience_nonnegative'),
    sa.CheckConstraint('required_quantity > 0', name='ck_staffing_quantity_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('staffing_requirement_id')
    )
    op.create_index(op.f('ix_staffing_requirements_project_id'), 'staffing_requirements', ['project_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('allocations',
    sa.Column('allocation_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('staffing_requirement_id', sa.String(length=36), nullable=True),
    sa.Column('allocation_percentage', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('allocated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allocation_percentage > 0 AND allocation_percentage <= 100', name='ck_allocation_percentage_range'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_allocation_date_range'),
    sa.ForeignKeyConstraint(['allocated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['staffing_requirement_id'], ['staffing_requirements.staffing_requirement_id'], ),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_index(op.f('ix_allocations_allocated_by'), 'allocations', ['allocated_by'], unique=False)
    op.create_index(op.f('ix_allocations_employee_id'), 'allocations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_allocations_project_id'), 'allocations', ['project_id'], unique=False)
    op.create_index(op.f('ix_allocations_staffing_requirement_id'), 'allocations', ['staffing_requirement_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('audit_event_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_event_id')
    )
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('staffing_requirement_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('eligibility_status', sa.String(length=50), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint('rank > 0', name='ck_recommendation_rank_positive'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['staffing_requirement_id'], ['staffing_requirements.staffing_requirement_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendations_employee_id'), 'recommendations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_recommendations_generated_by'), 'recommendations', ['generated_by'], unique=False)
    op.create_index(op.f('ix_recommendations_staffing_requirement_id'), 'recommendations', ['staffing_requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_staffing_requirement_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_generated_by'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_employee_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_allocations_staffing_requirement_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_project_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_employee_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_allocated_by'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_staffing_requirements_project_id'), table_name='staffing_requirements')
    op.drop_table('staffing_requirements')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_employee_skills_skill_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_certifications_employee_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_table('roles')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
