import {
  useCallback,
  useEffect,
  useMemo,
  useState,
} from 'react'
import { useSearchParams } from 'react-router-dom'
import type {
  RecommendationItem,
  RecommendationResponse,
} from '../types/recommendation'
import { generateRecommendations } from '../services/recommendations'
import './RecommendationsPage.css'

const VERIFIED_STAFFING_REQUIREMENT_ID =
  '5d3a37fc-cccf-4e24-bae2-d2fb6c175e23'

function RecommendationsPage() {
  const [searchParams] = useSearchParams()

  const requirementIdFromUrl =
    searchParams.get('requirementId')?.trim() ?? ''

  const initialRequirementId =
    requirementIdFromUrl ||
    VERIFIED_STAFFING_REQUIREMENT_ID

  const [
    staffingRequirementId,
    setStaffingRequirementId,
  ] = useState(initialRequirementId)

  const [result, setResult] =
    useState<RecommendationResponse | null>(null)

  const [loading, setLoading] = useState(false)

  const [error, setError] =
    useState<string | null>(null)

  const [generatedAt, setGeneratedAt] =
    useState<string | null>(null)

  const [autoGeneratedId, setAutoGeneratedId] =
    useState<string | null>(null)

  const handleGenerateRecommendations =
    useCallback(
      async (requirementIdOverride?: string) => {
        const requirementId = (
          requirementIdOverride ??
          staffingRequirementId
        ).trim()

        if (!requirementId) {
          setError(
            'Please enter a valid staffing requirement ID.',
          )
          return
        }

        setLoading(true)
        setError(null)
        setResult(null)

        try {
          const response =
            await generateRecommendations({
              staffing_requirement_id:
                requirementId,
            })

          setResult(response)
          setGeneratedAt(
            new Date().toLocaleString('en-IN'),
          )
        } catch (requestError) {
          const message =
            requestError instanceof Error
              ? requestError.message
              : 'Unable to generate recommendations.'

          setError(message)
        } finally {
          setLoading(false)
        }
      },
      [staffingRequirementId],
    )

  useEffect(() => {
    if (
      !requirementIdFromUrl ||
      autoGeneratedId === requirementIdFromUrl
    ) {
      return
    }

    // URL parameters are an external input to this page.
    // Synchronize the editable field once before auto-generating.
    // oxlint-disable-next-line react/set-state-in-effect
    setStaffingRequirementId(
      requirementIdFromUrl,
    )

    setAutoGeneratedId(requirementIdFromUrl)

    void Promise.resolve().then(() =>
      handleGenerateRecommendations(
        requirementIdFromUrl,
      ),
    )
  }, [
    requirementIdFromUrl,
    autoGeneratedId,
    handleGenerateRecommendations,
  ])

  const summary = useMemo(() => {
    const recommendations =
      result?.recommendations ?? []

    const eligible =
      recommendations.filter(
        (recommendation) =>
          recommendation.eligibility_status.toLowerCase() ===
          'eligible',
      ).length

    const topScore =
      recommendations.length > 0
        ? Math.max(
            ...recommendations.map(
              (recommendation) =>
                recommendation.score,
            ),
          )
        : 0

    const matchedSkills = new Set(
      recommendations.flatMap(
        (recommendation) =>
          recommendation.matched_skills,
      ),
    )

    return {
      candidates: recommendations.length,
      eligible,
      topScore,
      matchedSkills: matchedSkills.size,
    }
  }, [result])

  return (
    <main className="recommendations-page">
      <header className="recommendations-page-header">
        <div className="recommendations-page-heading">
          <span className="recommendations-eyebrow">
            WORKFORCE INTELLIGENCE
          </span>

          <h1>Recommendations</h1>

          <p>
            Review ranked workforce candidates for an
            open staffing requirement.
          </p>
        </div>

        <div className="recommendations-live-status">
          <span className="recommendations-live-dot" />
          LIVE MATCHING DATA
        </div>
      </header>

      <section
        className="recommendation-kpi-grid"
        aria-label="Recommendation summary"
      >
        <article className="recommendation-kpi-card">
          <div className="recommendation-kpi-icon recommendation-kpi-blue">
            #
          </div>

          <div className="recommendation-kpi-content">
            <span className="recommendation-kpi-label">
              CANDIDATES
            </span>

            <strong>{summary.candidates}</strong>

            <small>
              Ranked candidates returned
            </small>
          </div>
        </article>

        <article className="recommendation-kpi-card">
          <div className="recommendation-kpi-icon recommendation-kpi-green">
            ✓
          </div>

          <div className="recommendation-kpi-content">
            <span className="recommendation-kpi-label">
              ELIGIBLE
            </span>

            <strong>{summary.eligible}</strong>

            <small>
              Meeting eligibility rules
            </small>
          </div>
        </article>

        <article className="recommendation-kpi-card">
          <div className="recommendation-kpi-icon recommendation-kpi-purple">
            ★
          </div>

          <div className="recommendation-kpi-content">
            <span className="recommendation-kpi-label">
              TOP SCORE
            </span>

            <strong>{summary.topScore}</strong>

            <small>
              Highest recommendation score
            </small>
          </div>
        </article>

        <article className="recommendation-kpi-card">
          <div className="recommendation-kpi-icon recommendation-kpi-orange">
            ◇
          </div>

          <div className="recommendation-kpi-content">
            <span className="recommendation-kpi-label">
              MATCHED SKILLS
            </span>

            <strong>{summary.matchedSkills}</strong>

            <small>
              Unique skills matched
            </small>
          </div>
        </article>
      </section>

      <section className="recommendation-workspace">
        <article className="recommendation-panel recommendation-generation-panel">
          <div className="recommendation-panel-heading">
            <span className="recommendation-section-label">
              STAFFING REQUIREMENT
            </span>

            <h2>Generate Candidate Matches</h2>

            <p>
              Enter a staffing requirement ID to
              generate the ranked candidate list.
            </p>
          </div>

          <form
            className="recommendation-form"
            onSubmit={(event) => {
              event.preventDefault()
              void handleGenerateRecommendations()
            }}
          >
            <label
              htmlFor="staffing-requirement-id"
              className="recommendation-form-label"
            >
              Staffing Requirement ID
            </label>

            <div className="recommendation-input-row">
              <input
                id="staffing-requirement-id"
                type="text"
                value={staffingRequirementId}
                onChange={(event) =>
                  setStaffingRequirementId(
                    event.target.value,
                  )
                }
                placeholder="Enter staffing requirement ID"
                disabled={loading}
              />

              <button
                type="submit"
                disabled={
                  loading ||
                  !staffingRequirementId.trim()
                }
              >
                <span>
                  {loading
                    ? 'Generating...'
                    : 'Generate Recommendations'}
                </span>

                <span aria-hidden="true">→</span>
              </button>
            </div>
          </form>

          {loading && (
            <div className="recommendation-feedback recommendation-loading">
              <span className="recommendation-spinner" />

              <div>
                <strong>
                  Generating recommendations
                </strong>

                <span>
                  Evaluating workforce candidates against
                  the staffing requirement.
                </span>
              </div>
            </div>
          )}

          {error && (
            <div
              className="recommendation-feedback recommendation-error"
              role="alert"
            >
              <strong>
                Recommendation generation failed
              </strong>

              <span>{error}</span>
            </div>
          )}
        </article>

        <article className="recommendation-panel recommendation-context-panel">
          <div className="recommendation-context-heading">
            <div>
              <span className="recommendation-section-label">
                REQUIREMENT CONTEXT
              </span>

              <h2>Recommendation Run</h2>

              <p>
                Current recommendation request and
                execution details.
              </p>
            </div>

            <span
              className={`recommendation-status ${
                result
                  ? 'recommendation-status-generated'
                  : 'recommendation-status-ready'
              }`}
            >
              {result ? 'GENERATED' : 'READY'}
            </span>
          </div>

          <div className="recommendation-context-list">
            <div className="recommendation-context-item">
              <span>REQUIREMENT ID</span>

              <strong>
                {result?.staffing_requirement_id ??
                  staffingRequirementId}
              </strong>
            </div>

            <div className="recommendation-context-item">
              <span>RECOMMENDATIONS</span>

              <strong>
                {result
                  ? result.recommendations.length
                  : '—'}
              </strong>
            </div>

            <div className="recommendation-context-item">
              <span>GENERATED AT</span>

              <strong>
                {generatedAt ?? '—'}
              </strong>
            </div>

            <div className="recommendation-context-item">
              <span>SYSTEM MESSAGE</span>

              <strong>
                {result?.message ??
                  'No recommendation run executed yet.'}
              </strong>
            </div>
          </div>
        </article>
      </section>

      <section className="recommendation-panel recommendation-results-panel">
        <div className="recommendation-results-heading">
          <div>
            <span className="recommendation-section-label">
              CANDIDATE MATCHING
            </span>

            <h2>Ranked Candidates</h2>

            <p>
              Candidates are presented in the ranking
              returned by the workforce recommendation
              engine.
            </p>
          </div>

          <span className="recommendation-results-count">
            {summary.candidates} RESULTS
          </span>
        </div>

        {result &&
        result.recommendations.length > 0 ? (
          <div className="recommendation-list">
            {result.recommendations.map(
              (
                recommendation: RecommendationItem,
              ) => (
                <article
                  className="recommendation-card"
                  key={recommendation.employee_id}
                >
                  <div className="recommendation-rank">
                    #{recommendation.rank}
                  </div>

                  <div className="recommendation-card-body">
                    <div className="recommendation-card-heading">
                      <div>
                        <span className="recommendation-field-label">
                          EMPLOYEE
                        </span>

                        <h3>
                          {recommendation.employee_id}
                        </h3>
                      </div>

                      <div className="recommendation-score">
                        <span>SCORE</span>

                        <strong>
                          {recommendation.score}
                        </strong>
                      </div>
                    </div>

                    <div className="recommendation-card-meta">
                      <span
                        className={`recommendation-eligibility ${
                          recommendation.eligibility_status.toLowerCase() ===
                          'eligible'
                            ? 'recommendation-eligible'
                            : 'recommendation-not-eligible'
                        }`}
                      >
                        {recommendation.eligibility_status}
                      </span>

                      <span>
                        {
                          recommendation
                            .matched_skills.length
                        }{' '}
                        matched skill
                        {recommendation
                          .matched_skills.length !==
                        1
                          ? 's'
                          : ''}
                      </span>
                    </div>

                    <div className="recommendation-detail-grid">
                      <div className="recommendation-detail-block">
                        <span>
                          MATCHED SKILLS
                        </span>

                        <strong>
                          {recommendation
                            .matched_skills.length >
                          0
                            ? recommendation.matched_skills.join(
                                ', ',
                              )
                            : 'None'}
                        </strong>
                      </div>

                      <div className="recommendation-detail-block">
                        <span>REASON</span>

                        <strong>
                          {recommendation.reason}
                        </strong>
                      </div>
                    </div>
                  </div>
                </article>
              ),
            )}
          </div>
        ) : (
          <div className="recommendation-empty-state">
            <div className="recommendation-empty-icon">
              ✦
            </div>

            <strong>
              No recommendations generated yet
            </strong>

            <span>
              Enter a staffing requirement ID and
              generate candidate matches to view ranked
              results.
            </span>
          </div>
        )}
      </section>
    </main>
  )
}

export default RecommendationsPage